"""add log deatils

Revision ID: 721a1f0b9e32
Revises: 
Create Date: 2025-05-28 19:27:55.751524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '721a1f0b9e32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pd_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('pd_value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contact_sync_log', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('contact_sync_log', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('contact_sync_log', sa.Column('folder_id', sa.String(), nullable=True))
    op.add_column('contact_sync_log', sa.Column('folder_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_sync_log', 'folder_name')
    op.drop_column('contact_sync_log', 'folder_id')
    op.drop_column('contact_sync_log', 'last_name')
    op.drop_column('contact_sync_log', 'first_name')
    op.drop_table('scores')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
